### ISSUE TITLE
Option to resync with Twitch

### ISSUE THREAD

**Issue by DylanGuedes** [w3gvault/backend-api#1]
If you create a new account, and then update your profile on Twitch (such as your picture), w3gvault doesn't update it. I think that a option to resync it works great.

**Comment by anXieTyPB** [comment]
Twitch resync works properly if you re-authenticate with W3GVault after you changed your Twitch profile picture. If there was a logout-option that removed the token immediately you could trigger such a "resync" manually. Since it doesnt exist yet, you have to manually remove the token from the localStorage of your browser, change your Twitch Avatar and then re-authenticate in W3GVault using Twitch as a provider.
